### ISSUE TITLE
Visual Studio 2017 Error

### ISSUE THREAD

**Issue by royben** [antonio-bakula/ListDebuggerVisualizer#1]
Hey there,
I love this tool and use it for a couple of years now, so thanks!
I have used it successfully on VS 2013,2015, but now with 2017 I get this error.

 
![image](https://user-images.githubusercontent.com/1214312/29748358-f8d4659a-8b1d-11e7-85cc-0e2a183cf8c9.png)

Please help.

**Comment by antonio-bakula** [comment]
It works for me without problem:

![image](https://user-images.githubusercontent.com/7429672/29795879-758bd66e-8c4e-11e7-8972-1da392ebcfb1.png)

Could you please check that you have in ListDebuggerVisualizer.dll VS 2017 Visualizers user directory, for example: "c:\Users\username\Documents\Visual Studio 2017\Visualizers\ListDebuggerVisualizer.dll"

**Comment by Dallas411** [comment]
On some PCs I have the same problem, on others it works perfectly. Do you have any news? 

Thank you

Best regards

**Comment by achebrol** [comment]
unblocking(right click-> Properties -> Unblock) the ListDebuggerVisualizer.dll resolved the issue
