### ISSUE TITLE
Does it support net core projects?

### ISSUE THREAD

**Issue by paulovila** [antonio-bakula/ListDebuggerVisualizer#5]

**Comment by antonio-bakula** [comment]
No. I tried and it doesnt event start my visualizer. I will try to fix that.

**Comment by antonio-bakula** [comment]
It seems that there is a problem in Visual Studio and when they fix that it will work:
https://developercommunity.visualstudio.com/content/idea/351618/custom-debugger-visualizer-for-net-core-apps-in-vs.html

https://developercommunity.visualstudio.com/content/problem/562662/vs2019-custom-debugger-visualizer-for-net-fx-and-c.html
