### ISSUE TITLE
Enhancement: Debugee side

### ISSUE THREAD

**Issue by 5FEKO** [antonio-bakula/ListDebuggerVisualizer#6]
It is annoying that all data sources have to be [Serializable].

I think I found a workaround, by overriding on the Debugee side 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.debuggervisualizers.visualizerobjectsource.getdata?redirectedfrom=MSDN&view=visualstudiosdk-2017#remarks

so it serializes with JSON, then on the Debugger side, you can deserialize with JSON instead of BinaryFormatter by reading the Stream and not the object, i.e. GetData() instead of GetObject()

**Comment by antonio-bakula** [comment]
Well, it's really annoying and back then in 2012 there was no such option, so I lived with that but now there is no real reason :)
fixed in changeset 76ee0df59bc5c1d0560e017e912a8577dcc46731
