### ISSUE TITLE
Any plans to add this extension to the Visual Studio Marketplace?

### ISSUE THREAD

**Issue by stamminator** [antonio-bakula/ListDebuggerVisualizer#7]

**Comment by antonio-bakula** [comment]
Good idea, thanks !

Here it is: [https://marketplace.visualstudio.com/items?itemName=AntonioBakula.vs2019-list-visualizer](https://marketplace.visualstudio.com/items?itemName=AntonioBakula.vs2019-list-visualizer)

**Comment by stamminator** [comment]
Thanks! I would suggest adding this link to the readme file as well

**Comment by antonio-bakula** [comment]
done ! thanks again
