### ISSUE TITLE
Plugin not worked

### ISSUE THREAD

**Issue by cuban8IO** [antonio-bakula/ListDebuggerVisualizer#8]
Hi,
i use VS 2019. I've installed this plugin via marketplace, but it doesn't work. This messagebox comes up:

![image](https://user-images.githubusercontent.com/47720521/137471922-a37dfdc0-a79f-449b-bf74-70d84604e541.png)

Thank you!

**Comment by antonio-bakula** [comment]
Yes, it doesn't work for .net core, atleast not yet, sorry.

**Comment by cuban8IO** [comment]
Oh, okay. Would that be supported in the future? 
I use mostly .net5

**Comment by antonio-bakula** [comment]
Yes, it will be supported

**Comment by antonio-bakula** [comment]
Hello @cuban8IO 
I have working preview version that works with .NET Core debugee, you can wait unil #11 is done, and there is release for .NET Core with installer or download [this](http://www.antoniob.com/EasyEdit/UserFiles/Download/ListDebuggerVisualizer-dotNetCore.zip) and unpack in Visual Studio Visualizers directory
