### ISSUE TITLE
Visual Studio 2022 version

### ISSUE THREAD

**Issue by luisfco** [antonio-bakula/ListDebuggerVisualizer#9]
Nice work !!

Will there be a VS 2002 version ?

Thanks.

**Comment by aaxuan** [comment]
VS2022 Please.

**Comment by antonio-bakula** [comment]
I really don't see the need for List Visualizer in VS 2022 since there is one built in, and pretty decent one. Please commend and reopen this issue if you think that built in visualizer is not good enough. Thanks.
